export const GET_PROGRAMS = 'PROGRAMS/GET_PROGRAMS'

export const ADD_PROGRAM = 'PROGRAMS/ADD_PROGRAM'

export const UPDATE_PROGRAM = 'PROGRAMS/UPDATE_PROGRAM'

export const DELETE_PROGRAM = 'PROGRAMS/DELETE_PROGRAM'